### ISSUE TITLE
bgexclusion

### ISSUE THREAD

**Issue by Wty1122** [AsalJalilvand/Blood_Vessel_Segmentation#1]
What is the principle of this bgexclusion algorithm? I am a newbie who doesn't understand.

**Comment by AsalJalilvand** [comment]
Hello, 

Sorry for the late response!

I wrote this code based on the paper "[An Automated Blood Vessel Segmentation Algorithm Using Histogram Equalization and Automatic Threshold Selection](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3138933/)". 

I wrote it a long time ago and didn't really realized the importance of documentation, readability and reusability! Sorry about that :)

So, if you see go the link you will find a block diagram of the algorithm.
Start reading the code from "VesselSegmentation.m". You can match the blocks of the diagram with the code there easily. 
For most blocks you can easily call a Matlab function, but I had to implement most functions myself since it was course work.

the bgExclusion file is for the background exclusion. the idea is to remove background variation so that the foreground analysis would be easier. The code simply applies an average filter on the image and then subtracts the original from the filtered one. if the subtraction value for a pixel is less than zero, which is invalid, it just puts 0 in place of it. hope this helped.

**Comment by Wty1122** [comment]
> Hello,
> 
> Sorry for the late response!
> 
> I wrote this code based on the paper "[An Automated Blood Vessel Segmentation Algorithm Using Histogram Equalization and Automatic Threshold Selection](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3138933/)".
> 
> I wrote it a long time ago and didn't really realized the importance of documentation, readability and reusability! Sorry about that :)
> 
> So, if you go to the link, you will find a block diagram of the algorithm.
> Start reading the code from "VesselSegmentation.m". You can match the blocks of the diagram with the code there easily.
> For most blocks you can easily call a Matlab function, but I had to implement most functions myself since it was course work.
> 
> the bgExclusion file is for the background exclusion. the idea is to remove background variation so that the foreground analysis would be easier. The code simply applies an average filter on the image and then subtracts the original from the filtered one. if the subtraction value for a pixel is less than zero, which is invalid, it just puts 0 in place of it. hope this helped.

Thank you very much for your reply, these are very helpful to me, I will follow the link you gave to learn.
